name: Release eslint-plugin-react-css-cx
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./packages/eslint-plugin-react-css-cx
        run: yarn install
      - name: Build
        working-directory: ./packages/eslint-plugin-react-css-cx
        run: yarn build
      - name: Test
        working-directory: ./packages/eslint-plugin-react-css-cx
        run: yarn test
      - name: Release
        working-directory: ./packages/eslint-plugin-react-css-cx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release --debug
